<?php

namespace ContainerMMvaKKs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PPfHnkgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pPfHnkg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pPfHnkg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activitee' => ['privates', '.errored..service_locator.pPfHnkg.App\\Entity\\Activitee', NULL, 'Cannot autowire service ".service_locator.pPfHnkg": it references class "App\\Entity\\Activitee" but no such service exists.'],
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
        ], [
            'activitee' => 'App\\Entity\\Activitee',
            'categorieRepository' => 'App\\Repository\\CategorieRepository',
        ]);
    }
}
