<?php

namespace ContainerMMvaKKs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivitee5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.pPfHnkg.App\Entity\Activitee' shared service.
     *
     * @return \App\Entity\Activitee
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.pPfHnkg": it references class "App\\Entity\\Activitee" but no such service exists.');
    }
}
