<?php

namespace ContainerA9p5UxG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BPhLHGbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BPhLHGb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BPhLHGb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'parameterBag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'reclamation' => ['privates', '.errored..service_locator.BPhLHGb.App\\Entity\\Reclamation', NULL, 'Cannot autowire service ".service_locator.BPhLHGb": it references class "App\\Entity\\Reclamation" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'parameterBag' => '?',
            'reclamation' => 'App\\Entity\\Reclamation',
        ]);
    }
}
