<?php

namespace ContainerA9p5UxG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QVzVDNxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QVzVDNx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QVzVDNx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'equipement' => ['privates', '.errored..service_locator.QVzVDNx.App\\Entity\\Equipement', NULL, 'Cannot autowire service ".service_locator.QVzVDNx": it references class "App\\Entity\\Equipement" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'equipement' => 'App\\Entity\\Equipement',
        ]);
    }
}
