<?php

namespace ContainerA9p5UxG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MFB9V7gService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mFB9V7g' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mFB9V7g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'trajet' => ['privates', '.errored..service_locator.mFB9V7g.App\\Entity\\Trajet', NULL, 'Cannot autowire service ".service_locator.mFB9V7g": it references class "App\\Entity\\Trajet" but no such service exists.'],
        ], [
            'trajet' => 'App\\Entity\\Trajet',
        ]);
    }
}
