<?php

namespace ContainerA9p5UxG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RJDRji7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rJDRji7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rJDRji7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'trajetRepository' => ['privates', 'App\\Repository\\TrajetRepository', 'getTrajetRepositoryService', true],
        ], [
            'entityManager' => '?',
            'paginator' => '?',
            'trajetRepository' => 'App\\Repository\\TrajetRepository',
        ]);
    }
}
