<?php

namespace ContainerA9p5UxG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EfrlhyUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EfrlhyU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EfrlhyU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'logement' => ['privates', '.errored..service_locator.EfrlhyU.App\\Entity\\Logement', NULL, 'Cannot autowire service ".service_locator.EfrlhyU": it references class "App\\Entity\\Logement" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'logement' => 'App\\Entity\\Logement',
        ]);
    }
}
