<?php

namespace ContainerA9p5UxG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0eL4DFM.App\Entity\Logement' shared service.
     *
     * @return \App\Entity\Logement
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.0eL4DFM": it references class "App\\Entity\\Logement" but no such service exists.');
    }
}
