<?php

namespace ContainerA9p5UxG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMoyenTransport2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.OLwAQcP.App\Entity\MoyenTransport' shared service.
     *
     * @return \App\Entity\MoyenTransport
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.OLwAQcP": it references class "App\\Entity\\MoyenTransport" but no such service exists.');
    }
}
