<?php

namespace ContainerRZkAIVB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UDaC1rService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UDaC1r_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UDaC1r_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activiteeRepository' => ['privates', 'App\\Repository\\ActiviteeRepository', 'getActiviteeRepositoryService', true],
        ], [
            'activiteeRepository' => 'App\\Repository\\ActiviteeRepository',
        ]);
    }
}
