<?php

namespace ContainerRZkAIVB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9eIdrGjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9eIdrGj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9eIdrGj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'moyenTransportRepository' => ['privates', 'App\\Repository\\MoyenTransportRepository', 'getMoyenTransportRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'moyenTransportRepository' => 'App\\Repository\\MoyenTransportRepository',
            'paginator' => '?',
        ]);
    }
}
