<?php

namespace ContainerRZkAIVB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrajet2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.mFB9V7g.App\Entity\Trajet' shared service.
     *
     * @return \App\Entity\Trajet
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.mFB9V7g": it references class "App\\Entity\\Trajet" but no such service exists.');
    }
}
