<?php

namespace ContainerFSjZ7Di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fi90bxyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fi90bxy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fi90bxy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'trajet' => ['privates', '.errored..service_locator.fi90bxy.App\\Entity\\Trajet', NULL, 'Cannot autowire service ".service_locator.fi90bxy": it references class "App\\Entity\\Trajet" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'trajet' => 'App\\Entity\\Trajet',
        ]);
    }
}
