<?php

namespace ContainerFSjZ7Di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RBLm5kqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rBLm5kq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rBLm5kq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Repository' => ['privates', 'App\\Repository\\MoyenTransportRepository', 'getMoyenTransportRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'Repository' => 'App\\Repository\\MoyenTransportRepository',
            'paginator' => '?',
        ]);
    }
}
