<?php

namespace ContainerFSjZ7Di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0eL4DFMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0eL4DFM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0eL4DFM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'logement' => ['privates', '.errored..service_locator.0eL4DFM.App\\Entity\\Logement', NULL, 'Cannot autowire service ".service_locator.0eL4DFM": it references class "App\\Entity\\Logement" but no such service exists.'],
        ], [
            'logement' => 'App\\Entity\\Logement',
        ]);
    }
}
