<?php

namespace ContainerFSjZ7Di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LZtMC3YService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LZtMC3Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LZtMC3Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'equipement' => ['privates', '.errored..service_locator.LZtMC3Y.App\\Entity\\Equipement', NULL, 'Cannot autowire service ".service_locator.LZtMC3Y": it references class "App\\Entity\\Equipement" but no such service exists.'],
        ], [
            'equipement' => 'App\\Entity\\Equipement',
        ]);
    }
}
