<?php

namespace ContainerFSjZ7Di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendMailerServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SendMailerService' shared autowired service.
     *
     * @return \App\Service\SendMailerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'SendMailerService.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\Service\\SendMailerService'])) {
            return $container->privates['App\\Service\\SendMailerService'];
        }

        return $container->privates['App\\Service\\SendMailerService'] = new \App\Service\SendMailerService($a);
    }
}
