<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSpqBLgT\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSpqBLgT/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerSpqBLgT.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerSpqBLgT\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerSpqBLgT\App_KernelProdContainer([
    'container.build_hash' => 'SpqBLgT',
    'container.build_id' => 'a7702833',
    'container.build_time' => 1707856083,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSpqBLgT');
