<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MoyenTransport extends \App\Entity\MoyenTransport implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\MoyenTransport' . "\0" . 'id', '' . "\0" . 'App\\Entity\\MoyenTransport' . "\0" . 'type', '' . "\0" . 'App\\Entity\\MoyenTransport' . "\0" . 'capacite', '' . "\0" . 'App\\Entity\\MoyenTransport' . "\0" . 'lieu', '' . "\0" . 'App\\Entity\\MoyenTransport' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\MoyenTransport' . "\0" . 'trajets', '' . "\0" . 'App\\Entity\\MoyenTransport' . "\0" . 'valide', '' . "\0" . 'App\\Entity\\MoyenTransport' . "\0" . 'image'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\MoyenTransport' . "\0" . 'id', '' . "\0" . 'App\\Entity\\MoyenTransport' . "\0" . 'type', '' . "\0" . 'App\\Entity\\MoyenTransport' . "\0" . 'capacite', '' . "\0" . 'App\\Entity\\MoyenTransport' . "\0" . 'lieu', '' . "\0" . 'App\\Entity\\MoyenTransport' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\MoyenTransport' . "\0" . 'trajets', '' . "\0" . 'App\\Entity\\MoyenTransport' . "\0" . 'valide', '' . "\0" . 'App\\Entity\\MoyenTransport' . "\0" . 'image'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MoyenTransport $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(?string $type): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapacite(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapacite', []);

        return parent::getCapacite();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapacite(?int $capacite): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapacite', [$capacite]);

        return parent::setCapacite($capacite);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieu(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieu', []);

        return parent::getLieu();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieu(?string $lieu): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieu', [$lieu]);

        return parent::setLieu($lieu);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat(bool $etat): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrajets(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrajets', []);

        return parent::getTrajets();
    }

    /**
     * {@inheritDoc}
     */
    public function addTrajet(\App\Entity\Trajet $trajet): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTrajet', [$trajet]);

        return parent::addTrajet($trajet);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTrajet(\App\Entity\Trajet $trajet): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTrajet', [$trajet]);

        return parent::removeTrajet($trajet);
    }

    /**
     * {@inheritDoc}
     */
    public function isValide(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isValide', []);

        return parent::isValide();
    }

    /**
     * {@inheritDoc}
     */
    public function setValide(bool $valide): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValide', [$valide]);

        return parent::setValide($valide);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(string $image): \App\Entity\MoyenTransport
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

}
