<?php

namespace ContainerVdh5F1l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieAccRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CategorieAccRepository' shared autowired service.
     *
     * @return \App\Repository\CategorieAccRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CategorieAccRepository'] = new \App\Repository\CategorieAccRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
