<?php

namespace ContainerVdh5F1l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceVRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ServiceVRepository' shared autowired service.
     *
     * @return \App\Repository\ServiceVRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ServiceVRepository'] = new \App\Repository\ServiceVRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
