<?php

namespace ContainerVdh5F1l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserAddTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\UserAddType' shared autowired service.
     *
     * @return \App\Form\UserAddType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\UserAddType'] = new \App\Form\UserAddType();
    }
}
