#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_search:
    path: /restaurant/search
    controller: App\Controller\RestaurantController::search

statistics:
    path: /restaurant/statistics
    controller: App\Controller\RestaurantController::statistics



