#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logement_delete:
    path: /logement/{id}
    controller: App\Controller\LogementController::delete
    methods: POST 
deleteSelected:
    path: /logement/back/delete-selected
    controller: App\Controller\LogementController::deleteSelected
    methods: POST