<?php

namespace Container3eX5xdI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DOJgLh5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dOJgLh5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dOJgLh5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activitee' => ['privates', '.errored..service_locator.dOJgLh5.App\\Entity\\Activitee', NULL, 'Cannot autowire service ".service_locator.dOJgLh5": it references class "App\\Entity\\Activitee" but no such service exists.'],
        ], [
            'activitee' => 'App\\Entity\\Activitee',
        ]);
    }
}
