<?php

namespace Container3eX5xdI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActiviteeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IJqF3UI.App\Entity\Activitee' shared service.
     *
     * @return \App\Entity\Activitee
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.IJqF3UI": it references class "App\\Entity\\Activitee" but no such service exists.');
    }
}
