<?php

namespace ContainerQ4eirzN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BhFvWVGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bhFvWVG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bhFvWVG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'equipementRepository' => ['privates', 'App\\Repository\\EquipementRepository', 'getEquipementRepositoryService', true],
        ], [
            'equipementRepository' => 'App\\Repository\\EquipementRepository',
        ]);
    }
}
