<?php

namespace ContainerQ4eirzN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEquipementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LZtMC3Y.App\Entity\Equipement' shared service.
     *
     * @return \App\Entity\Equipement
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.LZtMC3Y": it references class "App\\Entity\\Equipement" but no such service exists.');
    }
}
