<?php

namespace ContainerQ4eirzN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrajetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fi90bxy.App\Entity\Trajet' shared service.
     *
     * @return \App\Entity\Trajet
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.fi90bxy": it references class "App\\Entity\\Trajet" but no such service exists.');
    }
}
