<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRZkAIVB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRZkAIVB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRZkAIVB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRZkAIVB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRZkAIVB\App_KernelDevDebugContainer([
    'container.build_hash' => 'RZkAIVB',
    'container.build_id' => 'b2183de3',
    'container.build_time' => 1709609097,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRZkAIVB');
