<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOXMVgcM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOXMVgcM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOXMVgcM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOXMVgcM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOXMVgcM\App_KernelDevDebugContainer([
    'container.build_hash' => 'OXMVgcM',
    'container.build_id' => '85d476bd',
    'container.build_time' => 1709607122,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOXMVgcM');
