<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX2DSPnb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX2DSPnb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX2DSPnb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX2DSPnb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX2DSPnb\App_KernelDevDebugContainer([
    'container.build_hash' => 'X2DSPnb',
    'container.build_id' => '5f4c3fbd',
    'container.build_time' => 1709591971,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX2DSPnb');
