<?php

namespace ContainerSpqBLgT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\FrontController' shared autowired service.
     *
     * @return \App\Controller\FrontController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\FrontController'] = $instance = new \App\Controller\FrontController();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\FrontController', $container));

        return $instance;
    }
}
