<?php

namespace ContainerSpqBLgT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdatePasswordTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\UpdatePasswordType' shared autowired service.
     *
     * @return \App\Form\UpdatePasswordType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\UpdatePasswordType'] = new \App\Form\UpdatePasswordType();
    }
}
